language: ruby
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
  matrix:
    - RAILS_VERSION="~> 3.0.0"
    - RAILS_VERSION="~> 3.1.0"
    - RAILS_VERSION="~> 3.2.0"
    - RAILS_VERSION="~> 4.0.0"
    - RAILS_VERSION="~> 4.1.0"
    - RAILS_VERSION="~> 4.2.0"
    - RAILS_VERSION="~> 5.0.0.beta1"
    - RAILS_VERSION="edge"
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
    - env: RAILS_VERSION="edge"
  fast_finish: true

sudo: false
